<ScreenOne>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            sizer_hint_y: 0.8
        TextInput:
            size_hint_y: 0.1
            id: user_query
        Button:
            text: 'Search Image'
            size_hint_y: 0.1
            on_press: root.get_image_link()


<RootWidget>:
    ScreenOne:
        id: screen_one
        name: 'screen_one'